### ISSUE TITLE
Polish Checklist

### ISSUE THREAD

**Issue by RiceCakess** [HolodexNet/Musicdex#4]
- [x] Fix safe space padding around drawer and android view
- [x] CLS improvements
- [x] Update sw caching rules for static files + channelImg
- [x] ~~Maybe add a meaningful share menu (Share to twitter/fb/discord/etc)~~ deprioritized
- [x] ~~Unify Playlist Header element~~ deprioritized
- [x] Add like button to music play bar
- [x] Add toast on Add to Queue
- [x] Fix emoji vs icon size on playlist side bar
- [x] Fix serviceworker update message
- [x] ~~Change carousel to snap list~~ (Edit: Reverted... NG)
- [x] A lot of input lag on production??? (Edit: Cannot reproduce)
- [x] Tweak org selector sidebar drop down (looks kinda weird)
- [x] Mobile does not have a way to play a single song (Clicking on title doesn't do anything)
- [x] Fix title size on playlist page
- [x] fix subttitle for auto generated playlist "streamed on: unreadable date"
- [x] change the random number "14" to "14 songs"
- [x] Clicking on a song in playlist page should set playlist and jump to song instead of queue up
- [x] Single song page sucks on mobile
- [x] Queue page needs a big polish (at least show current song)
- [x] Clean up channel page
  - [x]   > Popular songs should use song table
  - [x]   > latest stream should be less weird
  - [x]   > See all song page needs some polish
  - [x]     > Padding, and center of icon
  - [x]   > Queue All => Queue current (10)
  - [x]   > Pagination button should disable on page 1
  - [x]   > See all song button needs to be better positioned
  - [x]   > Social button cluster needs better colors and make it pop out more
  - [x]   > Font sizing needs adjustment (takes up too much space on smaller screens)
- [x] Virtualize recently played
- [x] Edit mode of table time needs fomratitng
- [x] Edit mode edit button should hide unless hovered?
- [x] User queries not reactive, eg. logging in wont fetch playlists
- [x] Logging out does not clear playlist
- [x] Org select needs to only drag on drag bars
- [x] Musicdex logo not showing up? on Mobile navbar
- [x] Navigating on mobile navbar doesn't close it
- [x] Lazy load home video carousel and playlist cards
